#You can change password here or from console with the command /securelogin setglobalpassword <password>
Password: "Hello1234"
Wrong-password-execute-commands:
  - "say hello"
  - "say %player has wrong the password"
  - "msg %player You've wrong the password"
Active-captcha: true
Active-password: true
Active-session: true