#You can change password here or from console with the command /securelogin setglobalpassword <password>
Password: "Hello1234"
Wrong-password-execute-commands:
  - "say hello"
  - "say %player has wrong the password"
  - "msg %player You've wrong the password"
Enable-captcha-protection: true
Enable-password-protection: true
Enable-session: true
#Worlds where the server will initiate player protection procedures
worlds:
  - "this_world"
  - "another_world"
  - "im_sad"